services:
    - docker

env:
    global:
        -  secure: "IFa/BVmFpOyBaNlIR3+3Req7h3yTQdnc7NniBh4uJBsATfY4LKvZpX84+lNgk2UD6LbaYNSV6F9RuGQ3qgu1qfYCiJOVlhAWt9TJQ092y4EnEKAfXFKJLBnYzwljjssKSOGpWD965SuKX32DCaHaLbhdjWX8hEw5m8JDtW9T5NQMlw5McXi222MKCxzfPaNwKoAMOXwUkCFF/lnaubEoDh6T7V58kBWsfcuKxssAo2SejOrYGKoDWC3jAqHW2ZZljJ0BQI8Ts+FFNxes373zt3Amy/DkQI/oUYA/1C0k98BeOga3Q8RKAWCEppnIUt1SDk/J/BYExn6XdLidIdOOh+aCXOpAJKZMO+rZGstWPyo4bvt05ULn9XcSaTS7eW5EfEcrWAs96e7+tOB3U62gOcor5uF9TZwMk9aZ42Fev+Z3VcBJhe9fxmNcpoBqASAflxLrH/LbMiFyc1nLnKkjCgZLEmf6X+/yKC2l3/D6ON+eNNszde96dC9f6tZbGIP9KaUELq+5rcWX8nZsINicIHtfQxPDj5UhfWZUms8wsAOO5Z1490E7WDPNLftoqVqQ4Ri46E11w508yTxB9ag+rNQHBJWNVHIHyJMMr/4SJv9qjbb2qE8+cxGx8oHyjKUYslRXhbgmS4X24uWy0YAHGgWzHBWkDlEtMVysvOrBUvw="

install:
    - docker build . -t empd2/empd-admin
    - echo GH_TOKEN=$GH_TOKEN > env.list

script:
    - docker run --env-file env.list empd2/empd-admin test-empd-admin -v
