services:
    - docker

env:
    global:
        -  secure: "IFa/BVmFpOyBaNlIR3+3Req7h3yTQdnc7NniBh4uJBsATfY4LKvZpX84+lNgk2UD6LbaYNSV6F9RuGQ3qgu1qfYCiJOVlhAWt9TJQ092y4EnEKAfXFKJLBnYzwljjssKSOGpWD965SuKX32DCaHaLbhdjWX8hEw5m8JDtW9T5NQMlw5McXi222MKCxzfPaNwKoAMOXwUkCFF/lnaubEoDh6T7V58kBWsfcuKxssAo2SejOrYGKoDWC3jAqHW2ZZljJ0BQI8Ts+FFNxes373zt3Amy/DkQI/oUYA/1C0k98BeOga3Q8RKAWCEppnIUt1SDk/J/BYExn6XdLidIdOOh+aCXOpAJKZMO+rZGstWPyo4bvt05ULn9XcSaTS7eW5EfEcrWAs96e7+tOB3U62gOcor5uF9TZwMk9aZ42Fev+Z3VcBJhe9fxmNcpoBqASAflxLrH/LbMiFyc1nLnKkjCgZLEmf6X+/yKC2l3/D6ON+eNNszde96dC9f6tZbGIP9KaUELq+5rcWX8nZsINicIHtfQxPDj5UhfWZUms8wsAOO5Z1490E7WDPNLftoqVqQ4Ri46E11w508yTxB9ag+rNQHBJWNVHIHyJMMr/4SJv9qjbb2qE8+cxGx8oHyjKUYslRXhbgmS4X24uWy0YAHGgWzHBWkDlEtMVysvOrBUvw="

install:
    - docker build . -t empd2/empd-admin
    - docker build docs -t empd2/empd-admin-docs
    - mkdir -p docs/_build/html

script:
    - docker run -e GH_TOKEN=$GH_TOKEN empd2/empd-admin test-empd-admin -v
    - docker run -v $(pwd)/docs/_build/html:/opt/empd-admin-docs empd2/empd-admin-docs build-empd-admin-docs /opt/empd-admin-docs

deploy:
  provider: pages
  skip-cleanup: true
  github-token:
    secure: "RJ0tutmOjquhgE7+TBXIJU/6KWxxR8uNGhoDDcCl4lNWsRVg3Vw8QByQktmaldRiQtcPl9yfxPX0PPSblF/kUjD4djecOf3P+45Q8sBrHgwnCQx7bS6fUJnUwxRCg5VcX1O+vjBFKA6jMW9qOngCIBFTDeeDU1CylffAwN/bTUEWZ79gzv41HUsr9VsbEtBUR2hSDiw3Y6ywWFynj+l1TUgGJwWI7hZ0noRS2lFG4yCgcwl5GQeNwSLs+LYx0cEGnFyLxCLwYumIsJEGPm17vYs9T08wX59mAP49mjqkjHZV2s0RaAOjM2J5qbNcMW+ZH2C8aWLyvSRYXVpMKvAJcZ4v6GSdVG+1d7qqLMiyU4amNSi4yHpwtVGcidRMgozhNqSa41PGyo7fSw5agg2k7jDAfCqJQ+BsciCxlQdz4yogkyjCa4xLSiWDKyZyP7Wy5qkxiGLa+I2gyvSdguWa4jYqGwkzMojS3+EBQvt0HQ+BZS/NnyQGFoRmeY98CQLsgDfxnnfMHaSMMXuIkTYDNziZ3wenvWcvkk+KG08GSWR3eQ2QnzN4faMVKaE70TyWK8QBSG8DdqCYSJiCIAnDszKkna4DzptvUsVkab9+bKd87K4vNzJO454q2vkPKskgGBhzEOA/RTGTgrv85nGfDoBWLjsJlkMwfx80OETGHmo="
  keep-history: true
  local-dir: docs/_build/html
  on:
    branch: master
