services:
    - docker

env:
    global:
        - secure: "tm6UOFJu9c/Icz4I2rx+WtyZW5MZfrVAhQe1LHrTCOUp014kyQXV0aJgCwAtR2IjsO7h7crKCOolg32XWBhbo65a5xcZbExPKEAhfP+fjRrSaKkgUO0cWcy6i4AjiednXeA5S4IfraqaroATUPMscQjZaI9o/B6eoSeu2Mcryq86q+ardcaNaAsWMQoT13tAZJMyfhTyOpNFR+PjHQWDhtVNB9MUq8SCEiU90S1eTOa6UG8ShBPzv0eEC0j80qGXn+Qf1Q+O/fm//yTA7w2h3Y9V/BIWqqcP1mh+50JVJcOa/bmZeCitnCbdojiqpbkzpUDUzitUv0fMbzv1JVu8SwA6jl2wtIGltxBqRd8X+FjJ7W0R3DIDuPT4KGAz8V76wazBySLTE57m3Y8h7lDka9bOGwejqC2P12ko52QC2+qH48DEvXu97j7AFTu2WP3n5puxFEQQ1D37EHf2H3oNwn4GgPDB+Qn0oXM/OyCFR6DH8FMoCL3hCXKPvpVAGvZw9+rcQH4lXZpTt+invNYh5MmJuIbeY3vQw4awZhk0M2FLzHCRiNlsc5AYc/gEg1ll1KCj9aeoUYN8VviQmYZ4Sdmd6+V73O8W3rgGN94UZE0IMqTYeGvH0kTYyYonEVY3G7nioXNe8AmCGlajQLnqOvu+/QN6FCKzIutIMF+AruY="
        - secure: "TbWTHlRaiV8hMJOxHrwxfJejUN4KvChX9B+1ez1NNc2RQ0Id953Mq6379qG9bpknUa1pcQfkYtV9jJRI5Drq7SgYixCRADzdf1kJwgxGvkgJ/yfXeihrlxn5w3Z416+RCna1M9cVGr855AmGl1/mBpWUVjmExygolNaBuRDvAIsZWonUiBrQsQ4DsRAtP+Ty4EyOh5P4D7bNUBf2bgXaGB4GYtf9X3y/cVePIXkra/e9Sh0hKL0Rr6MXUy2mJ3gxMJA0iGpm2YBSRiqBZ1x3+pILDqm2Nu+jOEzslFeVQVqY4v8n14hi2Te3K3zlhmd6xburKk2crdOXTDnMFYWafUdWxHGI++a4+nfZz7a8YucgvukQ8mj/S2kfQJ7Yn38zuBUJrVxEjz/J5LrXgb2628pGwfCIw8RwTQUUWQJjabKaYmeYiS3L2w3ZOlCnSYkrRtt3V2x5OWVS7psCMSRO9m5hcBEOzmVob7i4a+zkEY9tUQ/H/lXNAtp24AJ4XsBWTDSts6Ur+f1CP3CAaDC/g1j6wrfy+6E3Cv/qgNBnW5gCWX1Cf8ld9tJh5dOjvoQk7gmvLrrWFQqmkUTTX14va6z4ag90YG5/n6KqAt8agqucaR5ptp5cKVPdQYLkFlQXzTH5oHXCWyU27t0MnWV0nSS/Rwa513t/sQnbZ2h6GMs="

install:
    - docker build . -t empd2/empd-admin
    - echo GH_TOKEN=$GH_TOKEN > env.list

script:
    - docker run --env-file env.list empd2/empd-admin /bin/bash -c "cd /opt/empd-admin && py.test -v"

before_deploy:
    - rm env.list

deploy:
    provider: script
    script: bash docker_push.sh
    on:
        branch: master
